# Generated by Django 3.2.14 on 2022-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
